[package]
name = "download_sdl2"
version = "0.0.3"
authors = ["William Roe <git@wjlr.org.uk>"]
description = "A build helper for downloading SDL2 libraries"
license = "MIT"

[dependencies]
hyper = "0.10"
zip = "0.3"
glob = "0.2"
tar = "0.4"
flate2 = "1.0"

[lib]
doctest = false
